config/routes.rb
Pgpitter::Application.routes.draw do
  resources :statuses, only: [:create]

  resources :keys, only: [:show] do
    resources :statuses, only: [:index]
  end

  get "/about", to: "high_voltage/pages#show", id: "about"

  # statuses#show is hidden behind the hexid to maintain the small amount of
  # privacy that we think we have. This way people cannot just browse through
  # statuses by incrementing the ID.
  get "/:hexid(.:format)", to: "statuses#show", as: :hex
end

app/models/key.rb
require 'hkp'

class Key < ActiveRecord::Base
  has_many :signatures, foreign_key: :signed_key_id
  has_many :signers, through: :signatures, source: :signing_key, class_name: 'Key'
  has_many :statuses

  def formatted_keyid
    "0x#{keyid}"
  end

  def signers_statuses
    signers.map(&:statuses).flatten
  end

  def populate_signers!
    raw_signers_from_gnupg.each do |raw_signer|
      begin
        populate_signer(raw_signer)
      rescue ActiveRecord::RecordNotUnique
      end
    end
  end

  private

  def populate_signer(raw_signer)
    type, _, _, _, signer_keyid, _, _, _, _, name_and_email, _ = raw_signer.split(":")

    if ["sig", "rev"].include?(type)
      signer_key = Key.find_or_create_by!(keyid: signer_keyid)
      update_signer_key_with_uid_info(name_and_email, signer_key)
      signatures.create!(signing_key: signer_key)
    end
  end

  def update_signer_key_with_uid_info(name_and_email, signer_key)
    if name_and_email != "[User ID not found]"
      name, _email = name_and_email.split(" <")
      email = _email.chomp(">")
      signer_key.update(primary_name: name, primary_email: email)
    end
  end

  def raw_signers_from_gnupg
    `gpg --with-colons --list-sigs #{keyid}`.split("\n")
  end
end

app/models/sig_exception.rb
class SigException < StandardError
end

app/models/signature.rb
class Signature < ActiveRecord::Base
  belongs_to :signed_key, class_name: 'Key'
  belongs_to :signing_key, class_name: 'Key'
end

app/models/status.rb
require 'hkp'
require 'sig_exception'

class Status < ActiveRecord::Base
  belongs_to :key

  before_create :set_keyid, :set_hexid

  delegate :keyid, :formatted_keyid, to: :key

  def key_signer_count
    key.signers.count
  end

  def some_key_signers
    key.signers.limit(1)
  end

  def source_sig
    signed_body || signature
  end

  private

  def set_hexid
    self.hexid = SecureRandom.hex(4)
  end

  def set_keyid
    self.body, raw_key = verify
    self.key = Key.find_or_create_by(keyid: raw_key.primary_subkey.keyid)
    self.key.update(primary_name: raw_key.primary_uid.name, primary_email: raw_key.primary_uid.email)
  rescue ActiveRecord::ActiveRecordError => e
    self.error.add(e.message)
    false
  rescue GPGME::Error::NoData
    self.errors.add(:signed_body, "Invalid signature")
    false
  end

  def verify(tries = 2)
    sig = nil

    if self.body.present? && self.signature.present?
      crypto.verify(self.signature, signed_text: self.body) { | sig_ | sig = sig_ }
      verified_data(StringIO.new(body), sig, tries)
    else
      data = crypto.verify(signed_body){ | sig_ | sig = sig_ }
      verified_data(data, sig, tries)
    end
  end

  def verified_data(data, sig, tries)
    case GPGME.gpgme_err_code(sig.status)
    when GPGME::GPG_ERR_NO_ERROR
      [data.read, sig.key]
    when GPGME::GPG_ERR_NO_PUBKEY
      if tries > 0
        import_into_keyring(sig.fpr)
        verify(tries - 1)
      else
        raise SigException, "could not find public key for: #{sig.fpr}"
      end
    else
      raise SigException, sig.to_s
    end
  end

  def crypto
    GPGME::Crypto.new
  end

  def import_into_keyring(fingerprint)
    raw_pub_key = hkp.fetch(fingerprint)
    GPGME::Key.import(raw_pub_key)
  end

  def hkp
    Hkp.new(KEYSERVER_URL)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/keys_controller.rb
class KeysController < ApplicationController
  def show
    @key = Key.find_by_keyid!(params[:id].sub("0x", ""))
    @statuses = @key.statuses
  end
end

app/controllers/statuses_controller.rb
require 'sig_exception'

class StatusesController < ApplicationController
  def index
    key = Key.find_by_keyid(params[:key_id].sub("0x", ""))
    render text: key.statuses.map(&:source_sig).join("\n")
  end

  def create
    status = Status.new(status_params)
    if status.save
      status.key.populate_signers!
      response.headers['Location'] = hex_url(status.hexid)
      render text: '', status: 201
    else
      render text: status.errors.full_messages.join(', '), status: 400
    end
  rescue SigException => e
    render text: e.message, status: 400
  end

  def show
    status = Status.find_by_hexid(params[:hexid])
    respond_to do |format|
      format.html { @status = status }
      format.json { render json: status }
      format.asc  { render text: status.source_sig }
    end
  end

  private

  def status_params
    params.require(:status).permit(:signed_body, :body, :signature)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%= value %></div>
  <% end -%>
</div>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/keys/show.html.erb
<section class="posts">
  <h3><a href="https://pgp.mit.edu/pks/lookup?op=vindex&search=<%= @key.formatted_keyid %>" class="mit"><%= pluralize @key.signers.count, "person" %></a> trust that <%= @key.primary_name %> wrote these posts:</h3>

  <ul class="post-list">
    <% @statuses.each do |status| %>
      <li>
        <h4><%= link_to(truncate(status.body, length: 50, separator: ' '),
                      hex_path(status.hexid)) %></h4>
        <p>Posted <%= status.created_at.to_formatted_s(:month_and_year) %></p>
      </li>
    <% end %>
  <ul>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, :media => 'all' %>
  <meta name="viewport" content="width=device-width; initial-scale=1.0">
  <meta name="description" content="Post PGP-signed content without creating a username or password.">
  <link href='//fonts.googleapis.com/css?family=PT+Mono|Karla:400,400italic,700,700italic' rel='stylesheet' type='text/css'> 
  <%= csrf_meta_tags %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-54345105-1', 'auto');
    ga('send', 'pageview');
  </script>
</head>

<body class="<%= body_class %>">
  <header class="top-level-header">
    <h1><a href="/">mnfst.io</a></h1>
    <h2><%= link_to 'What is this?', page_path('about') %></h2>
  </header>

  <section class="container">
    <%= render 'flashes' -%>
    <%= yield %>
    <%= render 'javascript' %>
  </section>

  <footer>
    <p>A project by <a href="https://twitter.com/mikeburns">@mikeburns</a>, <a href="https://twitter.com/rmeritz">@rmeritz</a> & <a href="https://twitter.com/ubuwaits">@ubuwaits</a>. Grab the code on <a href="https://github.com/mnfst">GitHub</a>.</p>
  </footer>

</body>
</html>

app/views/pages/about.html.erb
<section class="about-page-content">
 <h3>What's this all about?</h3>
 <p>
 We want to share your content, and we want to <strong>confirm</strong> you
 support it.
 You want to post content, but you want to <strong>never send your password
   over the Internet</strong>.
 Together, let's use OpenPGP to digitally sign and post your document <strong>without
   ever making a new account</strong>.
 </p>

 <p>
 This Web site cannot be &ldquo;signed in to&rdquo;.
 Signing into a Web site is an old, antiquated idea.
 The future will be one where you sign data locally then host it remotely.
 Only a fool would type their password into a Web page.
 </p>

 <section>
   <h4>How it works, intermediate difficulty</h4>
   <ol>
     <li>
       <em>Make an OpenPGP key using GnuPG</em>.
       The software we provide depends on GnuPG (<code>gpg</code>) &mdash;
       specifically GPGME &mdash; so you must set up your private key using
       that. If you already have a private key then you should skip this step.
<pre>$ gpg --gen-key
$ gpg --send-key</pre>
     </li>
     <li>
       <em>Add our PGP public key to your keyring</em>.
       Our software is signed with our PGP key, so add it to your keyring.
       The master keyid is <code>0xFBAE90619F653118</code>.
       The fingerprint is <code>CFAF 2EA3 467D 54D6 A571  D3F0 FBAE 9061 9F65 3118</code>.
<pre>$ gpg --recv-key 0xFBAE90619F653118
$ gpg --fingerprint 0xFBAE90619F653118</pre>
     </li>
     <li>
       <em>Download and install mkmnfst</em>.
       The mkmnfst program depends on the libcurl and GPGME libraries and a C
       compiler.
       It is known to work on OpenBSD, Debian, and OS X.
       The release is signed with our PGP key.
       Our signing subkeys are <code>0xAFBF615D7661F82A</code> and
       <code>0x029477225FB26D83</code>.
<pre>$ curl -LO https://github.com/mnfst/mkmnfst/releases/download/v0.3/mkmnfst-0.3.tar.gz
$ curl -LO https://github.com/mnfst/mkmnfst/releases/download/v0.3/mkmnfst-0.3.tar.gz.asc
$ gpg --verify mkmnfst-0.3.tar.gz.asc mkmnfst-0.3.tar.gz
$ tar -zxf mkmnfst-0.3.tar.gz
$ cd mkmnfst
$ ./configure
$ make
$ sudo make install</pre>
     </li>
     <li>
       <em>Run mkmnfst on a file</em>.
       The hard part is done.
       <pre>$ mkmnfst proclaimation-to-the-world.txt</pre>
     </li>
   </ol>

   <h4>How it works, advanced difficulty</h4>
   <h5>JSON, attached signature</h5>
   <p>
   Let <var>$SIGNED_BODY</var> be a PGP-signed message in ASCII-armored
   format.
   You <em>must</em> make sure to preserve newlines in <var>$SIGNED_BODY</var>.
   If you encounter errors, first ensure that newlines are preserved.
   </p>
   <p>
   The JSON looks like this:
   </p>
   <pre>{"status":{"signed_body":<var>$SIGNED_BODY</var>}}</pre>
   <h5>JSON, detached signature</h5>
   <p>
   Let <var>$SIGNATURE</var> be a PGP signature in ASCII-armored
   format.
   You <em>must</em> make sure to preserve newlines in <var>$SIGNATURE</var>.
   If you encounter errors, first ensure that newlines are preserved.
   </p>
   <p>Let <var>$BODY</var> be the source text for the signature.</p>
   <p>
   The JSON looks like this:
   </p>
   <pre>{"status":{"body":<var>$BODY</var>,"signature":$SIGNATURE}}</pre>
   <h5>POST</h5>
   <p>POST the JSON to <code><%= statuses_url %></code></p>
  </section>
</section>

app/views/pages/home.html.erb
<section class="home-page-content">
 <h2>Don&rsquo;t Trust Us</h2>
 <h3>Post PGP-signed content without creating a username or password.</h3>
 <p class="cta-instructions"><%= link_to 'How to Post', page_path('about') %></p>
 <p class="post-link"><%= link_to 'Read a post', "/4e073a77" %></p>
</section>

app/views/statuses/show.html.erb
<section class="status">
  <section class="author-validation">
    <p><a href="https://pgp.mit.edu/pks/lookup?op=vindex&search=<%= @status.formatted_keyid %>" class="mit"><%= pluralize @status.key.signers.count, "person" %></a> trust that <%= link_to(@status.key.primary_name, key_path(@status.key.formatted_keyid)) %> wrote:</p>
  </section>

  <section class="status-body">
    <p><%= @status.body %></p>
  </section>

  <section class="status-date">
    <p>Posted <%= @status.created_at.to_formatted_s(:month_and_year) %></p>
  </section>
</section>

<section class="status-original">
<section class="status-original-body">
<pre>
<%= link_to(@status.source_sig, hex_path(@status.hexid, format:"asc"), title: "Download PGP-signed post") %>
</pre>
</section>
</section>